-- =============================================================================
-- Migration: create todos table
-- Created:   2026-01-01
-- =============================================================================

-- Enable the pgcrypto extension for gen_random_uuid() (no-op if already enabled)
create extension if not exists "pgcrypto";

-- -----------------------------------------------------------------------------
-- Table
-- -----------------------------------------------------------------------------

create table if not exists public.todos (
  id          uuid        primary key default gen_random_uuid(),
  user_id     uuid        not null references auth.users(id) on delete cascade,
  title       text        not null check (char_length(title) > 0),
  completed   boolean     not null default false,
  created_at  timestamptz not null default now()
);

-- Index speeds up the common query: "all todos for a user, newest first"
create index if not exists todos_user_id_created_at_idx
  on public.todos (user_id, created_at desc);

-- -----------------------------------------------------------------------------
-- Row-Level Security
-- -----------------------------------------------------------------------------

alter table public.todos enable row level security;

-- Users can only see their own todos
create policy "Users can view own todos"
  on public.todos
  for select
  using (auth.uid() = user_id);

-- Users can insert todos for themselves only
create policy "Users can insert own todos"
  on public.todos
  for insert
  with check (auth.uid() = user_id);

-- Users can update their own todos
create policy "Users can update own todos"
  on public.todos
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Users can delete their own todos
create policy "Users can delete own todos"
  on public.todos
  for delete
  using (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- Comments
-- -----------------------------------------------------------------------------

comment on table  public.todos              is 'Todo items owned by authenticated users.';
comment on column public.todos.id          is 'Primary key — UUID generated by the database.';
comment on column public.todos.user_id     is 'References auth.users; enforces ownership.';
comment on column public.todos.title       is 'Human-readable description of the todo item.';
comment on column public.todos.completed   is 'True when the user has marked the item done.';
comment on column public.todos.created_at  is 'UTC timestamp of row insertion.';
